import React, { createContext, useContext, useState, useEffect } from 'react';

// Available languages
export type Language = 'en' | 'es' | 'fr' | 'de' | 'ja';

// Language names for display
export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  ja: '日本語'
};

// Sample translations for demonstration
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar Menu
    dashboard: 'Dashboard',
    passwordVault: 'Password Vault',
    authentication: 'Authentication',
    securityStatus: 'Security Status',
    blockchainVerify: 'Blockchain Verify',
    securityVerification: 'Security Verification',
    encryptedMessaging: 'Encrypted Messaging',
    notifications: 'Notifications',
    settings: 'Settings',
    signOut: 'Sign Out',
    protected: 'Protected',
    lastScan: 'Last scan',
    
    // Settings Menu
    autoLock: 'Auto Lock',
    autoLockDesc: 'Lock app after period of inactivity',
    loginAlerts: 'Login Alerts',
    loginAlertsDesc: 'Get notified about login attempts',
    dataManagement: 'Data Management',
    exportData: 'Export Data',
    exportDesc: 'Download your stored data',
    syncFrequency: 'Sync Frequency',
    syncDesc: 'Control how often data syncs',
    clearData: 'Clear Data',
    clearDataDesc: 'Erase all local stored data',
    
    // Account Management Menu
    accountManagement: 'Account Management',
    premiumPlan: 'Premium Plan',
    planRenews: 'Plan renews on May 15, 2025',
    manageSubscription: 'Manage Subscription',
    deleteAccount: 'Delete Account',
    deleteConfirm: 'This action cannot be undone. This will permanently delete your account and remove all your data from our servers.',
    cancel: 'Cancel',
    
    // Admin
    admin: 'Admin',
    adminUsers: 'Users',
    'Admin Settings': 'Admin Settings',
    Security: 'Security',
    'User Policies': 'User Policies',
    System: 'System',
    'API & Integration': 'API & Integration',
    Important: 'Important',
    'Changes to these settings will affect all users on the platform. Please proceed with caution.': 'Changes to these settings will affect all users on the platform. Please proceed with caution.',

    // Admin Security Settings
    'Configure security policies for the platform': 'Configure security policies for the platform',
    'Enforce 2FA for all users': 'Enforce 2FA for all users',
    'All users will be required to set up two-factor authentication': 'All users will be required to set up two-factor authentication',
    'Strong Password Policy': 'Strong Password Policy',
    'Require complex passwords with numbers, symbols and uppercase letters': 'Require complex passwords with numbers, symbols and uppercase letters',
    'Maximum Login Attempts': 'Maximum Login Attempts',
    'Number of failed attempts before account lockout': 'Number of failed attempts before account lockout',
    'Session Timeout (minutes)': 'Session Timeout (minutes)',
    'Automatically log users out after period of inactivity': 'Automatically log users out after period of inactivity',
    'Encryption Settings': 'Encryption Settings',
    'Data encryption and protection configurations': 'Data encryption and protection configurations',
    'End-to-End Encryption': 'End-to-End Encryption',
    'Enable end-to-end encryption for all communications': 'Enable end-to-end encryption for all communications',
    'Encryption Algorithm': 'Encryption Algorithm',
    
    // Admin User Policies
    'Configure default settings for users': 'Configure default settings for users',
    'Periodic Password Reset': 'Periodic Password Reset',
    'Require users to reset passwords periodically': 'Require users to reset passwords periodically',
    'Password Expiry (days)': 'Password Expiry (days)',
    'Days before password must be changed': 'Days before password must be changed',
    'Allow Multiple Device Login': 'Allow Multiple Device Login',
    'Users can be logged in on multiple devices simultaneously': 'Users can be logged in on multiple devices simultaneously',
    'Maximum Devices Per User': 'Maximum Devices Per User', 
    'Maximum number of active devices per user': 'Maximum number of active devices per user',
    'User Activity Logging': 'User Activity Logging',
    'Track and log all user activities on the platform': 'Track and log all user activities on the platform',
    'Geographic Restrictions': 'Geographic Restrictions',
    'Enable location-based access restrictions': 'Enable location-based access restrictions',
    'Account lifecycle and access controls': 'Account lifecycle and access controls',
    'Account Inactivity Period': 'Account Inactivity Period',
    'Days before an inactive account is suspended': 'Days before an inactive account is suspended',
    'Automatic Account Recovery': 'Automatic Account Recovery',
    'Allow users to recover accounts without admin approval': 'Allow users to recover accounts without admin approval',
    'Allow Self Account Deletion': 'Allow Self Account Deletion',
    'Users can permanently delete their own accounts': 'Users can permanently delete their own accounts',
    
    // Admin System Settings
    'System Configuration': 'System Configuration',
    'Server and infrastructure settings': 'Server and infrastructure settings',
    'Maintenance Mode': 'Maintenance Mode',
    'Temporarily restrict access for non-admin users': 'Temporarily restrict access for non-admin users',
    'Automated Backups': 'Automated Backups',
    'Frequency of system-wide data backups': 'Frequency of system-wide data backups',
    'Debug Mode': 'Debug Mode',
    'Enable detailed logging for troubleshooting': 'Enable detailed logging for troubleshooting',
    'Data Retention Period': 'Data Retention Period',
    'How long to retain system logs and usage data': 'How long to retain system logs and usage data',
    'Performance Settings': 'Performance Settings',
    'System performance and optimization': 'System performance and optimization',
    'Resource Allocation': 'Resource Allocation',
    'Percentage of system resources allocated to core functions': 'Percentage of system resources allocated to core functions',
    'Cache Optimization': 'Cache Optimization',
    'Optimize system cache for faster performance': 'Optimize system cache for faster performance',
    'Automated Cleanup Interval': 'Automated Cleanup Interval',
    'Frequency of temporary file cleanup': 'Frequency of temporary file cleanup',
    'Run System Diagnostics': 'Run System Diagnostics',
    
    // Admin API Settings
    'API Settings': 'API Settings',
    'API keys and integration configurations': 'API keys and integration configurations',
    'Enable API Access': 'Enable API Access',
    'Allow external applications to access the API': 'Allow external applications to access the API',
    'API Rate Limit': 'API Rate Limit',
    'Maximum number of requests per minute': 'Maximum number of requests per minute',
    'API Key': 'API Key',
    'Generate': 'Generate',
    'This key grants full access to the API. Keep it secure.': 'This key grants full access to the API. Keep it secure.',
    'Access Controls': 'Access Controls',
    'Read Access': 'Read Access',
    'Allow retrieving data via API': 'Allow retrieving data via API',
    'Write Access': 'Write Access',
    'Allow modifying data via API': 'Allow modifying data via API',
    'Delete Access': 'Delete Access',
    'Allow deleting data via API': 'Allow deleting data via API',
    'Webhook Configuration': 'Webhook Configuration',
    'Configure webhook endpoints for event notifications': 'Configure webhook endpoints for event notifications',
    'Enable Webhooks': 'Enable Webhooks',
    'Send event notifications to external services': 'Send event notifications to external services',
    'Webhook URL': 'Webhook URL',
    'URL to receive event notifications': 'URL to receive event notifications',
    'Events to Send': 'Events to Send',
    'User Login': 'User Login',
    'New Account': 'New Account',
    'Password Change': 'Password Change',
    'Security Alerts': 'Security Alerts',
    'Test Webhook': 'Test Webhook',
  },
  es: {
    // Sidebar Menu
    dashboard: 'Panel Principal',
    passwordVault: 'Bóveda de Contraseñas',
    authentication: 'Autenticación',
    securityStatus: 'Estado de Seguridad',
    blockchainVerify: 'Verificación Blockchain',
    securityVerification: 'Verificación de Seguridad',
    encryptedMessaging: 'Mensajería Cifrada',
    notifications: 'Notificaciones',
    settings: 'Configuración',
    signOut: 'Cerrar Sesión',
    protected: 'Protegido',
    lastScan: 'Último escaneo',
    
    // Admin
    adminUsers: 'Usuarios',
    Security: 'Seguridad',
    'User Policies': 'Políticas de Usuario',
    System: 'Sistema',
    'API & Integration': 'API e Integración',
    'Admin Settings': 'Configuración de Administrador',
    Important: 'Importante',
    'Changes to these settings will affect all users on the platform. Please proceed with caution.': 'Los cambios en estas configuraciones afectarán a todos los usuarios de la plataforma. Por favor, proceda con precaución.',
    
    // Admin Security Settings
    'Configure security policies for the platform': 'Configurar políticas de seguridad para la plataforma',
    'Enforce 2FA for all users': 'Imponer 2FA para todos los usuarios',
    'All users will be required to set up two-factor authentication': 'Todos los usuarios deberán configurar la autenticación de dos factores',
    'Strong Password Policy': 'Política de Contraseñas Fuertes',
    'Require complex passwords with numbers, symbols and uppercase letters': 'Requerir contraseñas complejas con números, símbolos y letras mayúsculas',
    'Maximum Login Attempts': 'Máximo de Intentos de Inicio de Sesión',
    'Number of failed attempts before account lockout': 'Número de intentos fallidos antes del bloqueo de la cuenta',
    'Session Timeout (minutes)': 'Tiempo de Espera de Sesión (minutos)',
    'Automatically log users out after period of inactivity': 'Cerrar sesión automáticamente después de un período de inactividad',
    'Encryption Settings': 'Configuración de Cifrado',
    'Data encryption and protection configurations': 'Configuraciones de cifrado y protección de datos',
    'End-to-End Encryption': 'Cifrado de Extremo a Extremo',
    'Enable end-to-end encryption for all communications': 'Habilitar cifrado de extremo a extremo para todas las comunicaciones',
    'Encryption Algorithm': 'Algoritmo de Cifrado',
    
    // Admin User Policies
    'Configure default settings for users': 'Configurar ajustes predeterminados para usuarios',
    'Periodic Password Reset': 'Restablecimiento Periódico de Contraseña',
    'Require users to reset passwords periodically': 'Requerir que los usuarios restablezcan las contraseñas periódicamente',
    'Password Expiry (days)': 'Vencimiento de Contraseña (días)',
    'Days before password must be changed': 'Días antes de que se deba cambiar la contraseña',
    'Allow Multiple Device Login': 'Permitir Inicio de Sesión en Múltiples Dispositivos',
    'Users can be logged in on multiple devices simultaneously': 'Los usuarios pueden iniciar sesión en varios dispositivos simultáneamente',
    'Maximum Devices Per User': 'Máximo de Dispositivos Por Usuario', 
    'Maximum number of active devices per user': 'Número máximo de dispositivos activos por usuario',
    'User Activity Logging': 'Registro de Actividad del Usuario',
    'Track and log all user activities on the platform': 'Rastrear y registrar todas las actividades del usuario en la plataforma',
    'Geographic Restrictions': 'Restricciones Geográficas',
    'Enable location-based access restrictions': 'Habilitar restricciones de acceso basadas en la ubicación',
    'Account lifecycle and access controls': 'Ciclo de vida de la cuenta y controles de acceso',
    'Account Inactivity Period': 'Período de Inactividad de la Cuenta',
    'Days before an inactive account is suspended': 'Días antes de que se suspenda una cuenta inactiva',
    'Automatic Account Recovery': 'Recuperación Automática de Cuenta',
    'Allow users to recover accounts without admin approval': 'Permitir a los usuarios recuperar cuentas sin aprobación del administrador',
    'Allow Self Account Deletion': 'Permitir Eliminación Propia de Cuenta',
    'Users can permanently delete their own accounts': 'Los usuarios pueden eliminar permanentemente sus propias cuentas',
    
    // Admin System Settings
    'System Configuration': 'Configuración del Sistema',
    'Server and infrastructure settings': 'Configuraciones de servidor e infraestructura',
    'Maintenance Mode': 'Modo de Mantenimiento',
    'Temporarily restrict access for non-admin users': 'Restringir temporalmente el acceso para usuarios no administradores',
    'Automated Backups': 'Copias de Seguridad Automáticas',
    'Frequency of system-wide data backups': 'Frecuencia de copias de seguridad de datos de todo el sistema',
    'Debug Mode': 'Modo de Depuración',
    'Enable detailed logging for solución de problemas': 'Habilitar registro detallado para solución de problemas',
    'Data Retention Period': 'Período de Retención de Datos',
    'How long to retain system logs and usage data': 'Cuánto tiempo conservar los registros del sistema y datos de uso',
    'Performance Settings': 'Configuración de Rendimiento',
    'System performance and optimization': 'Rendimiento y optimización del sistema',
    'Resource Allocation': 'Asignación de Recursos',
    'Percentage of system resources allocated to core functions': 'Porcentaje de recursos del sistema asignados a funciones principales',
    'Cache Optimization': 'Optimización de Caché',
    'Optimize system cache for faster performance': 'Optimizar la caché del sistema para un rendimiento más rápido',
    'Automated Cleanup Interval': 'Intervalo de Limpieza Automática',
    'Frequency of temporary file cleanup': 'Frecuencia de limpieza de archivos temporales',
    'Run System Diagnostics': 'Ejecutar Diagnóstico del Sistema',
    
    // Admin API Settings
    'API Settings': 'Configuración de API',
    'API keys and integration configurations': 'Claves de API y configuraciones de integración',
    'Enable API Access': 'Habilitar Acceso a API',
    'Allow external applications to access the API': 'Permitir que aplicaciones externas accedan a la API',
    'API Rate Limit': 'Límite de Tasa de API',
    'Maximum number of requests per minute': 'Número máximo de solicitudes por minuto',
    'API Key': 'Clave de API',
    'Generate': 'Generar',
    'This key grants full access to the API. Keep it secure.': 'Esta clave otorga acceso completo a la API. Manténgala segura.',
    'Access Controls': 'Controles de Acceso',
    'Read Access': 'Acceso de Lectura',
    'Allow retrieving data via API': 'Permitir recuperar datos a través de la API',
    'Write Access': 'Acceso de Escritura',
    'Allow modifying data via API': 'Permitir modificar datos a través de la API',
    'Delete Access': 'Acceso de Eliminación',
    'Allow deleting data via API': 'Permitir eliminar datos a través de la API',
    'Webhook Configuration': 'Configuración de Webhook',
    'Configure webhook endpoints for event notifications': 'Configurar endpoints de webhook para notificaciones de eventos',
    'Enable Webhooks': 'Habilitar Webhooks',
    'Send event notifications to external services': 'Enviar notificaciones de eventos a servicios externos',
    'Webhook URL': 'URL de Webhook',
    'URL to receive event notifications': 'URL para recibir notificaciones de eventos',
    'Events to Send': 'Eventos para Enviar',
    'User Login': 'Inicio de Sesión de Usuario',
    'New Account': 'Nueva Cuenta',
    'Password Change': 'Cambio de Contraseña',
    'Security Alerts': 'Alertas de Seguridad',
    'Test Webhook': 'Probar Webhook',
  },
  fr: {
    // Sidebar Menu
    dashboard: 'Tableau de Bord',
    passwordVault: 'Coffre-fort de Mots de Passe',
    authentication: 'Authentification',
    securityStatus: 'État de Sécurité',
    blockchainVerify: 'Vérification Blockchain',
    securityVerification: 'Vérification de Sécurité',
    encryptedMessaging: 'Messagerie Chiffrée',
    notifications: 'Notifications',
    settings: 'Paramètres',
    signOut: 'Déconnexion',
    protected: 'Protégé',
    lastScan: 'Dernier scan',
    
    // Admin
    adminUsers: 'Utilisateurs',
    Security: 'Sécurité',
    'User Policies': 'Politiques Utilisateur',
    System: 'Système',
    'API & Integration': 'API et Intégration',
    'Admin Settings': 'Paramètres Administrateur',
    Important: 'Important',
    'Changes to these settings will affect all users on the platform. Please proceed with caution.': 'Les modifications apportées à ces paramètres affecteront tous les utilisateurs de la plateforme. Veuillez procéder avec prudence.',
    
    // Admin Security Settings
    'Configure security policies for the platform': 'Configurer les politiques de sécurité pour la plateforme',
    'Enforce 2FA for all users': 'Imposer 2FA pour tous les utilisateurs',
    'All users will be required to set up two-factor authentication': 'Tous les utilisateurs devront configurer l\'authentification à deux facteurs',
    'Strong Password Policy': 'Politique de Mot de Passe Fort',
    'Require complex passwords with numbers, symbols and uppercase letters': 'Exiger des mots de passe complexes avec chiffres, symboles et lettres majuscules',
    'Maximum Login Attempts': 'Nombre Maximal de Tentatives de Connexion',
    'Number of failed attempts before account lockout': 'Nombre de tentatives échouées avant verrouillage du compte',
    'Session Timeout (minutes)': 'Expiration de Session (minutes)',
    'Automatically log users out after period of inactivity': 'Déconnecter automatiquement les utilisateurs après une période d\'inactivité',
    'Encryption Settings': 'Paramètres de Chiffrement',
    'Data encryption and protection configurations': 'Configurations de chiffrement et de protection des données',
    'End-to-End Encryption': 'Chiffrement de Bout en Bout',
    'Enable end-to-end encryption for all communications': 'Activer le chiffrement de bout en bout pour toutes les communications',
    'Encryption Algorithm': 'Algorithme de Chiffrement',
    
    // Admin User Policies
    'Configure default settings for users': 'Configurer les paramètres par défaut pour les utilisateurs',
    'Periodic Password Reset': 'Réinitialisation Périodique du Mot de Passe',
    'Require users to reset passwords periodically': 'Obliger les utilisateurs à réinitialiser périodiquement leurs mots de passe',
    'Password Expiry (days)': 'Expiration du Mot de Passe (jours)',
    'Days before password must be changed': 'Jours avant que le mot de passe ne doive être changé',
    'Allow Multiple Device Login': 'Autoriser la Connexion sur Plusieurs Appareils',
    'Users can be logged in on multiple devices simultaneously': 'Les utilisateurs peuvent être connectés sur plusieurs appareils simultanément',
    'Maximum Devices Per User': 'Nombre Maximum d\'Appareils Par Utilisateur',
    'Maximum number of active devices per user': 'Nombre maximum d\'appareils actifs par utilisateur',
    'User Activity Logging': 'Journalisation des Activités Utilisateur',
    'Track and log all user activities on the platform': 'Suivre et enregistrer toutes les activités des utilisateurs sur la plateforme',
    'Geographic Restrictions': 'Restrictions Géographiques',
    'Enable location-based access restrictions': 'Activer les restrictions d\'accès basées sur la localisation',
    'Account lifecycle and access controls': 'Cycle de vie du compte et contrôles d\'accès',
    'Account Inactivity Period': 'Période d\'Inactivité du Compte',
    'Days before an inactive account is suspended': 'Jours avant qu\'un compte inactif ne soit suspendu',
    'Automatic Account Recovery': 'Récupération Automatique de Compte',
    'Allow users to recover accounts without admin approval': 'Permettre aux utilisateurs de récupérer leurs comptes sans approbation admin',
    'Allow Self Account Deletion': 'Autoriser la Suppression de son Propre Compte',
    'Users can permanently delete their own accounts': 'Les utilisateurs peuvent supprimer définitivement leurs propres comptes',
    
    // Admin System Settings
    'System Configuration': 'Configuration Système',
    'Server and infrastructure settings': 'Paramètres du serveur et de l\'infrastructure',
    'Maintenance Mode': 'Mode Maintenance',
    'Temporarily restrict access for non-admin users': 'Restreindre temporairement l\'accès aux utilisateurs non-administrateurs',
    'Automated Backups': 'Sauvegardes Automatiques',
    'Frequency of system-wide data backups': 'Fréquence des sauvegardes de données à l\'échelle du système',
    'Debug Mode': 'Mode Débogage',
    'Enable detailed logging for troubleshooting': 'Activer la journalisation détaillée pour le dépannage',
    'Data Retention Period': 'Période de Conservation des Données',
    'How long to retain system logs and usage data': 'Durée de conservation des journaux système et des données d\'utilisation',
    'Performance Settings': 'Paramètres de Performance',
    'System performance and optimization': 'Performance et optimisation du système',
    'Resource Allocation': 'Allocation de Ressources',
    'Percentage of system resources allocated to core functions': 'Pourcentage des ressources système allouées aux fonctions principales',
    'Cache Optimization': 'Optimisation du Cache',
    'Optimize system cache for faster performance': 'Optimiser le cache système pour des performances plus rapides',
    'Automated Cleanup Interval': 'Intervalle de Nettoyage Automatique',
    'Frequency of temporary file cleanup': 'Fréquence de nettoyage des fichiers temporaires',
    'Run System Diagnostics': 'Exécuter les Diagnostics Système',
    
    // Admin API Settings
    'API Settings': 'Paramètres API',
    'API keys and integration configurations': 'Clés API et configurations d\'intégration',
    'Enable API Access': 'Activer l\'Accès API',
    'Allow external applications to access the API': 'Permettre aux applications externes d\'accéder à l\'API',
    'API Rate Limit': 'Limite de Taux API',
    'Maximum number of requests per minute': 'Nombre maximum de requêtes par minute',
    'API Key': 'Clé API',
    'Generate': 'Générer',
    'This key grants full access to the API. Keep it secure.': 'Cette clé donne un accès complet à l\'API. Gardez-la sécurisée.',
    'Access Controls': 'Contrôles d\'Accès',
    'Read Access': 'Accès en Lecture',
    'Allow retrieving data via API': 'Permettre de récupérer des données via l\'API',
    'Write Access': 'Accès en Écriture',
    'Allow modifying data via API': 'Permettre de modifier des données via l\'API',
    'Delete Access': 'Accès en Suppression',
    'Allow deleting data via API': 'Permettre de supprimer des données via l\'API',
    'Webhook Configuration': 'Configuration Webhook',
    'Configure webhook endpoints for event notifications': 'Configurer les endpoints webhook pour les notifications d\'événements',
    'Enable Webhooks': 'Activer les Webhooks',
    'Send event notifications to external services': 'Envoyer des notifications d\'événements à des services externes',
    'Webhook URL': 'URL Webhook',
    'URL to receive event notifications': 'URL pour recevoir les notifications d\'événements',
    'Events to Send': 'Événements à Envoyer',
    'User Login': 'Connexion Utilisateur',
    'New Account': 'Nouveau Compte',
    'Password Change': 'Changement de Mot de Passe',
    'Security Alerts': 'Alertes de Sécurité',
    'Test Webhook': 'Tester le Webhook',
  },
  de: {
    // Sidebar Menu
    dashboard: 'Dashboard',
    passwordVault: 'Passwort-Tresor',
    authentication: 'Authentifizierung',
    securityStatus: 'Sicherheitsstatus',
    blockchainVerify: 'Blockchain-Verifizierung',
    securityVerification: 'Sicherheitsüberprüfung',
    encryptedMessaging: 'Verschlüsselte Nachrichten',
    notifications: 'Benachrichtigungen',
    settings: 'Einstellungen',
    signOut: 'Abmelden',
    protected: 'Geschützt',
    lastScan: 'Letzter Scan',
    
    // Admin
    adminUsers: 'Benutzer',
    Security: 'Sicherheit',
    'User Policies': 'Benutzerrichtlinien',
    System: 'System',
    'API & Integration': 'API und Integration',
    'Admin Settings': 'Admin-Einstellungen',
    Important: 'Wichtig',
    'Changes to these settings will affect all users on the platform. Please proceed with caution.': 'Änderungen an diesen Einstellungen betreffen alle Benutzer der Plattform. Bitte gehen Sie vorsichtig vor.',
    
    // Admin Security Settings
    'Configure security policies for the platform': 'Sicherheitsrichtlinien für die Plattform konfigurieren',
    'Enforce 2FA for all users': 'Zwei-Faktor-Authentifizierung für alle Benutzer erzwingen',
    'All users will be required to set up two-factor authentication': 'Alle Benutzer müssen eine Zwei-Faktor-Authentifizierung einrichten',
    'Strong Password Policy': 'Strenge Passwortrichtlinie',
    'Require complex passwords with numbers, symbols and uppercase letters': 'Komplexe Passwörter mit Zahlen, Symbolen und Großbuchstaben erforderlich',
    'Maximum Login Attempts': 'Maximale Anmeldeversuche',
    'Number of failed attempts before account lockout': 'Anzahl der fehlgeschlagenen Versuche vor Kontosperrung',
    'Session Timeout (minutes)': 'Sitzungs-Timeout (Minuten)',
    'Automatically log users out after period of inactivity': 'Benutzer nach einer Inaktivitätsperiode automatisch abmelden',
    'Encryption Settings': 'Verschlüsselungseinstellungen',
    'Data encryption and protection configurations': 'Datenverschlüsselung und Schutzkonfigurationen',
    'End-to-End Encryption': 'Ende-zu-Ende-Verschlüsselung',
    'Enable end-to-end encryption for all communications': 'Ende-zu-Ende-Verschlüsselung für alle Kommunikationen aktivieren',
    'Encryption Algorithm': 'Verschlüsselungsalgorithmus',
    
    // Admin User Policies
    'Configure default settings for users': 'Standardeinstellungen für Benutzer konfigurieren',
    'Periodic Password Reset': 'Regelmäßige Passwortzurücksetzung',
    'Require users to reset passwords periodically': 'Benutzer müssen Passwörter regelmäßig zurücksetzen',
    'Password Expiry (days)': 'Passwortablauf (Tage)',
    'Days before password must be changed': 'Tage, bevor das Passwort geändert werden muss',
    'Allow Multiple Device Login': 'Anmeldung auf mehreren Geräten erlauben',
    'Users can be logged in on multiple devices simultaneously': 'Benutzer können gleichzeitig auf mehreren Geräten angemeldet sein',
    'Maximum Devices Per User': 'Maximale Geräte pro Benutzer',
    'Maximum number of active devices per user': 'Maximale Anzahl aktiver Geräte pro Benutzer',
    'User Activity Logging': 'Protokollierung von Benutzeraktivitäten',
    'Track and log all user activities on the platform': 'Alle Benutzeraktivitäten auf der Plattform verfolgen und protokollieren',
    'Geographic Restrictions': 'Geografische Einschränkungen',
    'Enable location-based access restrictions': 'Standortbasierte Zugriffsbeschränkungen aktivieren',
    'Account lifecycle and access controls': 'Lebenszyklus von Konten und Zugriffskontrollen',
    'Account Inactivity Period': 'Kontoinaktivitätszeitraum',
    'Days before an inactive account is suspended': 'Tage, bevor ein inaktives Konto gesperrt wird',
    'Automatic Account Recovery': 'Automatische Kontowiederherstellung',
    'Allow users to recover accounts without admin approval': 'Benutzer können Konten ohne Admin-Genehmigung wiederherstellen',
    'Allow Self Account Deletion': 'Selbstlöschung des Kontos erlauben',
    'Users can permanently delete their own accounts': 'Benutzer können ihre eigenen Konten dauerhaft löschen',
    
    // Admin System Settings
    'System Configuration': 'Systemkonfiguration',
    'Server and infrastructure settings': 'Server- und Infrastruktureinstellungen',
    'Maintenance Mode': 'Wartungsmodus',
    'Temporarily restrict access for non-admin users': 'Zugriff für Nicht-Administrator-Benutzer vorübergehend einschränken',
    'Automated Backups': 'Automatisierte Sicherungen',
    'Frequency of system-wide data backups': 'Häufigkeit systemweiter Datensicherungen',
    'Debug Mode': 'Debug-Modus',
    'Enable detailed logging for troubleshooting': 'Detaillierte Protokollierung zur Fehlerbehebung aktivieren',
    'Data Retention Period': 'Datenspeicherzeitraum',
    'How long to retain system logs and usage data': 'Wie lange Systemprotokolle und Nutzungsdaten aufbewahrt werden sollen',
    'Performance Settings': 'Leistungseinstellungen',
    'System performance and optimization': 'Systemleistung und Optimierung',
    'Resource Allocation': 'Ressourcenzuweisung',
    'Percentage of system resources allocated to core functions': 'Prozentsatz der Systemressourcen, die für Kernfunktionen zugewiesen sind',
    'Cache Optimization': 'Cache-Optimierung',
    'Optimize system cache for faster performance': 'Systemcache für schnellere Leistung optimieren',
    'Automated Cleanup Interval': 'Automatisches Bereinigungsintervall',
    'Frequency of temporary file cleanup': 'Häufigkeit der temporären Dateiaufräumung',
    'Run System Diagnostics': 'Systemdiagnose ausführen',
    
    // Admin API Settings
    'API Settings': 'API-Einstellungen',
    'API keys and integration configurations': 'API-Schlüssel und Integrationskonfigurationen',
    'Enable API Access': 'API-Zugriff aktivieren',
    'Allow external applications to access the API': 'Externen Anwendungen Zugriff auf die API erlauben',
    'API Rate Limit': 'API-Ratenbegrenzung',
    'Maximum number of requests per minute': 'Maximale Anzahl von Anfragen pro Minute',
    'API Key': 'API-Schlüssel',
    'Generate': 'Generieren',
    'This key grants full access to the API. Keep it secure.': 'Dieser Schlüssel gewährt vollen Zugriff auf die API. Bewahren Sie ihn sicher auf.',
    'Access Controls': 'Zugriffskontrollen',
    'Read Access': 'Lesezugriff',
    'Allow retrieving data via API': 'Ermöglicht das Abrufen von Daten über die API',
    'Write Access': 'Schreibzugriff',
    'Allow modifying data via API': 'Ermöglicht das Ändern von Daten über die API',
    'Delete Access': 'Löschzugriff',
    'Allow deleting data via API': 'Ermöglicht das Löschen von Daten über die API',
    'Webhook Configuration': 'Webhook-Konfiguration',
    'Configure webhook endpoints for event notifications': 'Konfigurieren von Webhook-Endpunkten für Ereignisbenachrichtigungen',
    'Enable Webhooks': 'Webhooks aktivieren',
    'Send event notifications to external Dienste': 'Ereignisbenachrichtigungen an externe Dienste senden',
    'Webhook URL': 'Webhook-URL',
    'URL to receive event notifications': 'URL zum Empfang von Ereignisbenachrichtigungen',
    'Events to Send': 'Zu sendende Ereignisse',
    'User Login': 'Benutzeranmeldung',
    'New Account': 'Neues Konto',
    'Password Change': 'Passwortänderung',
    'Security Alerts': 'Sicherheitshinweise',
    'Test Webhook': 'Webhook testen',
  },
  ja: {
    // Sidebar Menu
    dashboard: 'ダッシュボード',
    passwordVault: 'パスワード保管庫',
    authentication: '認証',
    securityStatus: 'セキュリティ状態',
    blockchainVerify: 'ブロックチェーン検証',
    securityVerification: 'セキュリティ検証',
    encryptedMessaging: '暗号化メッセージング',
    notifications: '通知',
    settings: '設定',
    signOut: 'サインアウト',
    protected: '保護済み',
    lastScan: '最終スキャン',
    
    // Admin
    adminUsers: 'ユーザー',
    Security: 'セキュリティ',
    'User Policies': 'ユーザーポリシー',
    System: 'システム',
    'API & Integration': 'APIと統合',
    'Admin Settings': '管理者設定',
    Important: '重要',
    'Changes to these settings will affect all users on the platform. Please proceed with caution.': 'これらの設定を変更すると、プラットフォーム上のすべてのユーザーに影響します。慎重に進めてください。',
    
    // Admin Security Settings
    'Configure security policies for the platform': 'プラットフォームのセキュリティポリシーを設定',
    'Enforce 2FA for all users': 'すべてのユーザーに2FA認証を強制',
    'All users will be required to set up two-factor authentication': 'すべてのユーザーは二要素認証を設定する必要があります',
    'Strong Password Policy': '強力なパスワードポリシー',
    'Require complex passwords with numbers, symbols and uppercase letters': '数字、記号、大文字を含む複雑なパスワードが必要',
    'Maximum Login Attempts': '最大ログイン試行回数',
    'Number of failed attempts before account lockout': 'アカウントロックアウトまでの失敗試行回数',
    'Session Timeout (minutes)': 'セッションタイムアウト（分）',
    'Automatically log users out after period of inactivity': '一定期間の非アクティブ後に自動ログアウト',
    'Encryption Settings': '暗号化設定',
    'Data encryption and protection configurations': 'データ暗号化と保護の設定',
    'End-to-End Encryption': 'エンドツーエンド暗号化',
    'Enable end-to-end encryption for all communications': 'すべての通信にエンドツーエンド暗号化を有効化',
    'Encryption Algorithm': '暗号化アルゴリズム',
    
    // Admin User Policies
    'Configure default settings for users': 'ユーザーのデフォルト設定を構成',
    'Periodic Password Reset': '定期的なパスワードリセット',
    'Require users to reset passwords periodically': 'ユーザーは定期的にパスワードをリセットする必要があります',
    'Password Expiry (days)': 'パスワード有効期限（日）',
    'Days before password must be changed': 'パスワード変更が必要になるまでの日数',
    'Allow Multiple Device Login': '複数デバイスでのログインを許可',
    'Users can be logged in on multiple devices simultaneously': 'ユーザーは複数のデバイスで同時にログイン可能',
    'Maximum Devices Per User': 'ユーザーあたりの最大デバイス数',
    'Maximum number of active devices per user': 'ユーザーあたりのアクティブなデバイスの最大数',
    'User Activity Logging': 'ユーザー活動のログ記録',
    'Track and log all user activities on the platform': 'プラットフォーム上のすべてのユーザー活動を追跡・記録',
    'Geographic Restrictions': '地理的制限',
    'Enable location-based access restrictions': '位置情報に基づくアクセス制限を有効化',
    'Account lifecycle and access controls': 'アカウントのライフサイクルとアクセス制御',
    'Account Inactivity Period': 'アカウント非アクティブ期間',
    'Days before an inactive account is suspended': '非アクティブなアカウントが停止されるまでの日数',
    'Automatic Account Recovery': '自動アカウント回復',
    'Allow users to recover accounts without admin approval': '管理者の承認なしでユーザーがアカウントを回復できるようにする',
    'Allow Self Account Deletion': 'アカウントの自己削除を許可',
    'Users can permanently delete their own accounts': 'ユーザーが自分のアカウントを完全に削除可能',
    
    // Admin System Settings
    'System Configuration': 'システム設定',
    'Server and infrastructure settings': 'サーバーとインフラストラクチャの設定',
    'Maintenance Mode': 'メンテナンスモード',
    'Temporarily restrict access for non-admin users': '非管理者ユーザーのアクセスを一時的に制限',
    'Automated Backups': '自動バックアップ',
    'Frequency of system-wide data backups': 'システム全体のデータバックアップの頻度',
    'Debug Mode': 'デバッグモード',
    'Enable detailed logging for troubleshooting': 'トラブルシューティング用の詳細なログ記録を有効化',
    'Data Retention Period': 'データ保持期間',
    'How long to retain system logs and usage data': 'システムログと使用データを保持する期間',
    'Performance Settings': 'パフォーマンス設定',
    'System performance and optimization': 'システムパフォーマンスと最適化',
    'Resource Allocation': 'リソース割り当て',
    'Percentage of system resources allocated to core functions': '基幹機能に割り当てるシステムリソースの割合',
    'Cache Optimization': 'キャッシュ最適化',
    'Optimize system cache for faster performance': '高速なパフォーマンスのためのシステムキャッシュの最適化',
    'Automated Cleanup Interval': '自動クリーンアップ間隔',
    'Frequency of temporary file cleanup': '一時ファイルのクリーンアップ頻度',
    'Run System Diagnostics': 'システム診断を実行',
    
    // Admin API Settings
    'API Settings': 'API設定',
    'API keys and integration configurations': 'APIキーと統合設定',
    'Enable API Access': 'APIアクセスを有効化',
    'Allow external applications to access the API': '外部アプリケーションがAPIにアクセスすることを許可',
    'API Rate Limit': 'APIレート制限',
    'Maximum number of requests per minute': '1分あたりの最大リクエスト数',
    'API Key': 'APIキー',
    'Generate': '生成',
    'This key grants full access to the API. Keep it secure.': 'このキーはAPIへの完全なアクセスを許可します。安全に保管してください。',
    'Access Controls': 'アクセス制御',
    'Read Access': '読み取りアクセス',
    'Allow retrieving data via API': 'API経由でのデータ取得を許可',
    'Write Access': '書き込みアクセス',
    'Allow modifying data via API': 'API経由でのデータ変更を許可',
    'Delete Access': '削除アクセス',
    'Allow deleting data via API': 'API経由でのデータ削除を許可',
    'Webhook Configuration': 'Webhook設定',
    'Configure webhook endpoints for event notifications': 'イベント通知用のWebhookエンドポイントを設定',
    'Enable Webhooks': 'Webhookを有効化',
    'Send event notifications to external services': '外部サービスにイベント通知を送信',
    'Webhook URL': 'Webhook URL',
    'URL to receive event notifications': 'イベント通知を受け取るURL',
    'Events to Send': '送信するイベント',
    'User Login': 'ユーザーログイン',
    'New Account': '新規アカウント',
    'Password Change': 'パスワード変更',
    'Security Alerts': 'セキュリティアラート',
    'Test Webhook': 'Webhookテスト',
  }
};

const LanguageContext = createContext<{
  language: Language;
  setLanguage: React.Dispatch<React.SetStateAction<Language>>;
  t: (key: string) => string;
}>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{children: React.ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get from localStorage or use browser language or default to English
    const saved = localStorage.getItem('language') as Language;
    if (saved && Object.keys(languageNames).includes(saved)) {
      return saved;
    }
    
    // Try to use browser language
    const browserLang = navigator.language.split('-')[0] as Language;
    if (Object.keys(languageNames).includes(browserLang)) {
      return browserLang;
    }
    
    return 'en';
  });

  // Save to localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    if (translations.en[key]) {
      return translations.en[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);